# Generated by Django 2.1.7 on 2019-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('desciption', models.CharField(max_length=400)),
            ],
        ),
    ]
