# Generated by Django 2.1.7 on 2019-04-01 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190331_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='desciption',
            new_name='content',
        ),
    ]
